# Generated by Django 3.2.3 on 2021-05-21 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('breeed', models.CharField(max_length=100, unique=True)),
                ('location_of_origin', models.CharField(max_length=100)),
                ('coat_length', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
            ],
        ),
    ]
